#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,prometheus
#  server:
#    address: localhost
#    port: 8072
#  prometheus:
#    metrics:
#      export:
#        enabled: true
#security:
#  basic:
#    enabled: false
server:
  port: 8060
#  address: 0.0.0.0
jwt:
  secret: moj-sekretowy-klucz
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin123
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        order_inserts: true
    show-sql: false

    # stripe: stripetestbokszczanin@gmail.com / UT-gq*cYG8MFtr3 / Stripe Bokszczanin
    # gmail: stripetestbokszczanin@gmail.com / Admin123!